CREATE TABLE `mailer_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`isDefault` boolean NOT NULL DEFAULT false,
	`companyName` varchar(255),
	`tagline` text,
	`logoUrl` text,
	`logoKey` text,
	`primaryColor` varchar(16) DEFAULT '#0EA875',
	`phone` varchar(32),
	`licenseNumber` varchar(64),
	`website` varchar(255),
	`coverHeadline` text,
	`coverSubheadline` text,
	`letterOpening` text,
	`letterBody` text,
	`letterClosing` text,
	`signatureName` varchar(255),
	`signatureTitle` varchar(255),
	`signatureImageUrl` text,
	`offerHeadline` text,
	`offerDetails` text,
	`ctaText` varchar(128),
	`warrantyYears` int DEFAULT 10,
	`warrantyDetails` text,
	`referralBonus` varchar(128),
	`referralDetails` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mailer_templates_id` PRIMARY KEY(`id`)
);
